version: '3.8'
services:
  back:
    container_name: back
    image: acrusba.azurecr.io/back
    platform: linux/amd64
    restart: always
    build: ./api
    ports:
      - "8001:8001"

  front:
    container_name: front
    image: acrusba.azurecr.io/front
    platform: linux/amd64
    build:
      context: front/
      target: prod
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_API_VERSION=${VITE_API_VERSION}
    ports:
      - "80:80"
