/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    LoginView: typeof import('./../src/views/LoginView.vue')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    PredictView: typeof import('./../src/views/PredictView.vue')['default']
    RegAutocomplete: typeof import('./../src/components/inputs/RegAutocomplete.vue')['default']
    RegButton: typeof import('./../src/components/inputs/RegButton.vue')['default']
    RegErrorText: typeof import('./../src/components/inputs/RegErrorText.vue')['default']
    RegInputText: typeof import('./../src/components/inputs/RegInputText.vue')['default']
    RegSwitch: typeof import('./../src/components/inputs/RegSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../src/components/SideBar.vue')['default']
    StoreRecordsTable: typeof import('./../src/components/StoreRecordsTable.vue')['default']
  }
}
