/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    ErrorText: typeof import('./../src/components/ErrorText.vue')['default']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    LoginView: typeof import('./../src/views/LoginView.vue')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    PredictView: typeof import('./../src/views/PredictView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupView: typeof import('./../src/views/SignupView.vue')['default']
    VerifyView: typeof import('./../src/views/VerifyView.vue')['default']
  }
}
